return {
	--{
	--	"zbirenbaum/copilot.lua",
	--	cmd = "Copilot",
	--	event = "InsertEnter",
	--	config = function()
	--		require("copilot").setup({})
	--	end,
	--},
	--{
	--	"yetone/avante.nvim",
	--	event = "VeryLazy",
	--	version = "0.0.23", -- Never set this value to "*"! Never!
	--	opts = {
	--		---@alias Provider "claude" | "openai" | "azure" | "gemini" | "cohere" | "copilot" | string
	--		provider = "copilot",
	--		copilot = {
	--			model = "claude-3.7-sonnet",
	--			-- model = "gemini-2.5-pro",
	--		},
	--	},
	--	build = "make",
	--	dependencies = {
	--		"nvim-treesitter/nvim-treesitter",
	--		"stevearc/dressing.nvim",
	--		"nvim-lua/plenary.nvim",
	--		"MunifTanjim/nui.nvim",
	--		--- The below dependencies are optional,
	--		-- "echasnovski/mini.pick", -- for file_selector provider mini.pick
	--		-- "ibhagwan/fzf-lua", -- for file_selector provider fzf
	--		-- "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
	--		"zbirenbaum/copilot.lua", -- for providers='copilot'
	--		{
	--			-- support for image pasting
	--			"HakonHarnes/img-clip.nvim",
	--			event = "VeryLazy",
	--			opts = {
	--				-- recommended settings
	--				default = {
	--					embed_image_as_base64 = false,
	--					prompt_for_file_name = false,
	--					drag_and_drop = {
	--						insert_mode = true,
	--					},
	--					-- required for Windows users
	--					-- use_absolute_path = true,
	--				},
	--			},
	--		},
	--		{
	--			-- Make sure to set this up properly if you have lazy=true
	--			"MeanderingProgrammer/render-markdown.nvim",
	--			opts = {
	--				file_types = { "markdown", "Avante" },
	--			},
	--			ft = { "markdown", "Avante" },
	--		},
	--	},
	--},
}
